# Generated by Django 6.0.7 on 2026-07-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='team/')),
                ('biography', models.TextField(blank=True)),
                ('favorite_scripture', models.TextField(blank=True)),
                ('quote', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Founder',
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About Page', 'verbose_name_plural': 'About Page'},
        ),
    ]
