# Generated by Django 6.0.7 on 2026-07-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teammember_delete_founder_alter_aboutpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='empowermentprogram',
            options={'verbose_name': 'Empowerment Program', 'verbose_name_plural': 'Empowerment Programs'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='empowermentprogram',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
