# Generated by Django 6.0.7 on 2026-08-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_series_order_alter_category_slug_and_more'),
        ('core', '0003_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='title',
            new_name='name',
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('series', 'series_order'), name='unique_series_post_order'),
        ),
    ]
