# Generated by Django 6.0.7 on 2026-08-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_title_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='name',
            new_name='title',
        ),
    ]
