# Generated by Django 6.0.8 on 2026-09-19 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_rename_name_post_title_rename_name_series_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog.series",
            ),
        ),
    ]
